version: '3'
services:

    web:
        container_name: laravel-pro-kit
        image: laravel-pro-kit
        build: .
        volumes:
            - .:/var/www/html
        ports:
            - "80:80"
        networks:
            - laravel-network
        depends_on:
            - mysql

    mysql:
        image: mysql:8.1.0
        container_name: laravel-mysql
        volumes:
            - mysql-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root_password
            MYSQL_DATABASE: laravel_db
            MYSQL_USER: laravel_user
            MYSQL_PASSWORD: laravel_password
        ports:
            - "3306:3306"
        networks:
            - laravel-network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: laravel-phpmyadmin
        links:
            - mysql
        ports:
            - "8080:80"  # Expose PHPMyAdmin on port 80
        environment:
            PMA_HOST: mysql
        networks:
            - laravel-network

networks:
    laravel-network:
        driver: bridge

volumes:
    mysql-data:
